<?php
/**
 * MailChimp Lists plugin for Craft CMS 3.x
 *
 * Create, manage and monitor your MailChimp Lists from within Craft.
 *
 * @link      https://github.com/lukeyouell
 * @copyright Copyright (c) 2018 Luke Youell
 */

namespace lukeyouell\mailchimplists\models;

use lukeyouell\mailchimplists\MailchimpLists;

use Craft;
use craft\base\Model;

/**
 * @author    Luke Youell
 * @package   MailchimpLists
 * @since     0.1.0
 */
class Settings extends Model
{
    // Public Properties
    // =========================================================================

    /**
     * @var string
     */
    public $apiKey = null;

    /**
     * @var string
     */
    public $countries = [
      ['value' => 'GB', 'label' => 'GB - United Kingdom'],
      ['value' => 'US', 'label' => 'US - United States'],
      ['value' => '', 'label' => '----'],
      ['value' => 'AD', 'label' => 'AD - Andorra'],
      ['value' => 'AE', 'label' => 'AE - United Arab Emirates'],
      ['value' => 'AF', 'label' => 'AF - Afghanistan'],
      ['value' => 'AG', 'label' => 'AG - Antigua and Barbuda'],
      ['value' => 'AI', 'label' => 'AI - Anguilla'],
      ['value' => 'AL', 'label' => 'AL - Albania'],
      ['value' => 'AM', 'label' => 'AM - Armenia'],
      ['value' => 'AO', 'label' => 'AO - Angola'],
      ['value' => 'AP', 'label' => 'AP - Asia/Pacific Region'],
      ['value' => 'AQ', 'label' => 'AQ - Antarctica'],
      ['value' => 'AR', 'label' => 'AR - Argentina'],
      ['value' => 'AS', 'label' => 'AS - American Samoa'],
      ['value' => 'AT', 'label' => 'AT - Austria'],
      ['value' => 'AU', 'label' => 'AU - Australia'],
      ['value' => 'AW', 'label' => 'AW - Aruba'],
      ['value' => 'AX', 'label' => 'AX - Aland Islands'],
      ['value' => 'AZ', 'label' => 'AZ - Azerbaijan'],
      ['value' => 'BA', 'label' => 'BA - Bosnia and Herzegovina'],
      ['value' => 'BB', 'label' => 'BB - Barbados'],
      ['value' => 'BD', 'label' => 'BD - Bangladesh'],
      ['value' => 'BE', 'label' => 'BE - Belgium'],
      ['value' => 'BF', 'label' => 'BF - Burkina Faso'],
      ['value' => 'BG', 'label' => 'BG - Bulgaria'],
      ['value' => 'BH', 'label' => 'BH - Bahrain'],
      ['value' => 'BI', 'label' => 'BI - Burundi'],
      ['value' => 'BJ', 'label' => 'BJ - Benin'],
      ['value' => 'BL', 'label' => 'BL - Saint Bartelemey'],
      ['value' => 'BM', 'label' => 'BM - Bermuda'],
      ['value' => 'BN', 'label' => 'BN - Brunei Darussalam'],
      ['value' => 'BO', 'label' => 'BO - Bolivia'],
      ['value' => 'BQ', 'label' => 'BQ - Bonaire, Saint Eustatius and Saba'],
      ['value' => 'BR', 'label' => 'BR - Brazil'],
      ['value' => 'BS', 'label' => 'BS - Bahamas'],
      ['value' => 'BT', 'label' => 'BT - Bhutan'],
      ['value' => 'BV', 'label' => 'BV - Bouvet Island'],
      ['value' => 'BW', 'label' => 'BW - Botswana'],
      ['value' => 'BY', 'label' => 'BY - Belarus'],
      ['value' => 'BZ', 'label' => 'BZ - Belize'],
      ['value' => 'CA', 'label' => 'CA - Canada'],
      ['value' => 'CC', 'label' => 'CC - Cocos (Keeling) Islands'],
      ['value' => 'CD', 'label' => 'CD - Congo, The Democratic Republic of the'],
      ['value' => 'CF', 'label' => 'CF - Central African Republic'],
      ['value' => 'CG', 'label' => 'CG - Congo'],
      ['value' => 'CH', 'label' => 'CH - Switzerland'],
      ['value' => 'CI', 'label' => 'CI - Cote d\'Ivoire'],
      ['value' => 'CK', 'label' => 'CK - Cook Islands'],
      ['value' => 'CL', 'label' => 'CL - Chile'],
      ['value' => 'CM', 'label' => 'CM - Cameroon'],
      ['value' => 'CN', 'label' => 'CN - China'],
      ['value' => 'CO', 'label' => 'CO - Colombia'],
      ['value' => 'CR', 'label' => 'CR - Costa Rica'],
      ['value' => 'CU', 'label' => 'CU - Cuba'],
      ['value' => 'CV', 'label' => 'CV - Cape Verde'],
      ['value' => 'CW', 'label' => 'CW - Curacao'],
      ['value' => 'CX', 'label' => 'CX - Christmas Island'],
      ['value' => 'CY', 'label' => 'CY - Cyprus'],
      ['value' => 'CZ', 'label' => 'CZ - Czech Republic'],
      ['value' => 'DE', 'label' => 'DE - Germany'],
      ['value' => 'DJ', 'label' => 'DJ - Djibouti'],
      ['value' => 'DK', 'label' => 'DK - Denmark'],
      ['value' => 'DM', 'label' => 'DM - Dominica'],
      ['value' => 'DO', 'label' => 'DO - Dominican Republic'],
      ['value' => 'DZ', 'label' => 'DZ - Algeria'],
      ['value' => 'EC', 'label' => 'EC - Ecuador'],
      ['value' => 'EE', 'label' => 'EE - Estonia'],
      ['value' => 'EG', 'label' => 'EG - Egypt'],
      ['value' => 'EH', 'label' => 'EH - Western Sahara'],
      ['value' => 'ER', 'label' => 'ER - Eritrea'],
      ['value' => 'ES', 'label' => 'ES - Spain'],
      ['value' => 'ET', 'label' => 'ET - Ethiopia'],
      ['value' => 'EU', 'label' => 'EU - Europe'],
      ['value' => 'FI', 'label' => 'FI - Finland'],
      ['value' => 'FJ', 'label' => 'FJ - Fiji'],
      ['value' => 'FK', 'label' => 'FK - Falkland Islands (Malvinas)'],
      ['value' => 'FM', 'label' => 'FM - Micronesia, Federated States of'],
      ['value' => 'FO', 'label' => 'FO - Faroe Islands'],
      ['value' => 'FR', 'label' => 'FR - France'],
      ['value' => 'GA', 'label' => 'GA - Gabon'],
      ['value' => 'GD', 'label' => 'GD - Grenada'],
      ['value' => 'GE', 'label' => 'GE - Georgia'],
      ['value' => 'GF', 'label' => 'GF - French Guiana'],
      ['value' => 'GG', 'label' => 'GG - Guernsey'],
      ['value' => 'GH', 'label' => 'GH - Ghana'],
      ['value' => 'GI', 'label' => 'GI - Gibraltar'],
      ['value' => 'GL', 'label' => 'GL - Greenland'],
      ['value' => 'GM', 'label' => 'GM - Gambia'],
      ['value' => 'GN', 'label' => 'GN - Guinea'],
      ['value' => 'GP', 'label' => 'GP - Guadeloupe'],
      ['value' => 'GQ', 'label' => 'GQ - Equatorial Guinea'],
      ['value' => 'GR', 'label' => 'GR - Greece'],
      ['value' => 'GS', 'label' => 'GS - South Georgia and the South Sandwich Islands'],
      ['value' => 'GT', 'label' => 'GT - Guatemala'],
      ['value' => 'GU', 'label' => 'GU - Guam'],
      ['value' => 'GW', 'label' => 'GW - Guinea-Bissau'],
      ['value' => 'GY', 'label' => 'GY - Guyana'],
      ['value' => 'HK', 'label' => 'HK - Hong Kong'],
      ['value' => 'HM', 'label' => 'HM - Heard Island and McDonald Islands'],
      ['value' => 'HN', 'label' => 'HN - Honduras'],
      ['value' => 'HR', 'label' => 'HR - Croatia'],
      ['value' => 'HT', 'label' => 'HT - Haiti'],
      ['value' => 'HU', 'label' => 'HU - Hungary'],
      ['value' => 'ID', 'label' => 'ID - Indonesia'],
      ['value' => 'IE', 'label' => 'IE - Ireland'],
      ['value' => 'IL', 'label' => 'IL - Israel'],
      ['value' => 'IM', 'label' => 'IM - Isle of Man'],
      ['value' => 'IN', 'label' => 'IN - India'],
      ['value' => 'IO', 'label' => 'IO - British Indian Ocean Territory'],
      ['value' => 'IQ', 'label' => 'IQ - Iraq'],
      ['value' => 'IR', 'label' => 'IR - Iran, Islamic Republic of'],
      ['value' => 'IS', 'label' => 'IS - Iceland'],
      ['value' => 'IT', 'label' => 'IT - Italy'],
      ['value' => 'JE', 'label' => 'JE - Jersey'],
      ['value' => 'JM', 'label' => 'JM - Jamaica'],
      ['value' => 'JO', 'label' => 'JO - Jordan'],
      ['value' => 'JP', 'label' => 'JP - Japan'],
      ['value' => 'KE', 'label' => 'KE - Kenya'],
      ['value' => 'KG', 'label' => 'KG - Kyrgyzstan'],
      ['value' => 'KH', 'label' => 'KH - Cambodia'],
      ['value' => 'KI', 'label' => 'KI - Kiribati'],
      ['value' => 'KM', 'label' => 'KM - Comoros'],
      ['value' => 'KN', 'label' => 'KN - Saint Kitts and Nevis'],
      ['value' => 'KP', 'label' => 'KP - Korea, Democratic People\'s Republic of'],
      ['value' => 'KR', 'label' => 'KR - Korea, Republic of'],
      ['value' => 'KW', 'label' => 'KW - Kuwait'],
      ['value' => 'KY', 'label' => 'KY - Cayman Islands'],
      ['value' => 'KZ', 'label' => 'KZ - Kazakhstan'],
      ['value' => 'LA', 'label' => 'LA - Lao People\'s Democratic Republic'],
      ['value' => 'LB', 'label' => 'LB - Lebanon'],
      ['value' => 'LC', 'label' => 'LC - Saint Lucia'],
      ['value' => 'LI', 'label' => 'LI - Liechtenstein'],
      ['value' => 'LK', 'label' => 'LK - Sri Lanka'],
      ['value' => 'LR', 'label' => 'LR - Liberia'],
      ['value' => 'LS', 'label' => 'LS - Lesotho'],
      ['value' => 'LT', 'label' => 'LT - Lithuania'],
      ['value' => 'LU', 'label' => 'LU - Luxembourg'],
      ['value' => 'LV', 'label' => 'LV - Latvia'],
      ['value' => 'LY', 'label' => 'LY - Libyan Arab Jamahiriya'],
      ['value' => 'MA', 'label' => 'MA - Morocco'],
      ['value' => 'MC', 'label' => 'MC - Monaco'],
      ['value' => 'MD', 'label' => 'MD - Moldova, Republic of'],
      ['value' => 'ME', 'label' => 'ME - Montenegro'],
      ['value' => 'MF', 'label' => 'MF - Saint Martin'],
      ['value' => 'MG', 'label' => 'MG - Madagascar'],
      ['value' => 'MH', 'label' => 'MH - Marshall Islands'],
      ['value' => 'MK', 'label' => 'MK - Macedonia'],
      ['value' => 'ML', 'label' => 'ML - Mali'],
      ['value' => 'MM', 'label' => 'MM - Myanmar'],
      ['value' => 'MN', 'label' => 'MN - Mongolia'],
      ['value' => 'MO', 'label' => 'MO - Macao'],
      ['value' => 'MP', 'label' => 'MP - Northern Mariana Islands'],
      ['value' => 'MQ', 'label' => 'MQ - Martinique'],
      ['value' => 'MR', 'label' => 'MR - Mauritania'],
      ['value' => 'MS', 'label' => 'MS - Montserrat'],
      ['value' => 'MT', 'label' => 'MT - Malta'],
      ['value' => 'MU', 'label' => 'MU - Mauritius'],
      ['value' => 'MV', 'label' => 'MV - Maldives'],
      ['value' => 'MW', 'label' => 'MW - Malawi'],
      ['value' => 'MX', 'label' => 'MX - Mexico'],
      ['value' => 'MY', 'label' => 'MY - Malaysia'],
      ['value' => 'MZ', 'label' => 'MZ - Mozambique'],
      ['value' => 'NA', 'label' => 'NA - Namibia'],
      ['value' => 'NC', 'label' => 'NC - New Caledonia'],
      ['value' => 'NE', 'label' => 'NE - Niger'],
      ['value' => 'NF', 'label' => 'NF - Norfolk Island'],
      ['value' => 'NG', 'label' => 'NG - Nigeria'],
      ['value' => 'NI', 'label' => 'NI - Nicaragua'],
      ['value' => 'NL', 'label' => 'NL - Netherlands'],
      ['value' => 'NO', 'label' => 'NO - Norway'],
      ['value' => 'NP', 'label' => 'NP - Nepal'],
      ['value' => 'NR', 'label' => 'NR - Nauru'],
      ['value' => 'NU', 'label' => 'NU - Niue'],
      ['value' => 'NZ', 'label' => 'NZ - New Zealand'],
      ['value' => 'OM', 'label' => 'OM - Oman'],
      ['value' => 'PA', 'label' => 'PA - Panama'],
      ['value' => 'PE', 'label' => 'PE - Peru'],
      ['value' => 'PF', 'label' => 'PF - French Polynesia'],
      ['value' => 'PG', 'label' => 'PG - Papua New Guinea'],
      ['value' => 'PH', 'label' => 'PH - Philippines'],
      ['value' => 'PK', 'label' => 'PK - Pakistan'],
      ['value' => 'PL', 'label' => 'PL - Poland'],
      ['value' => 'PM', 'label' => 'PM - Saint Pierre and Miquelon'],
      ['value' => 'PN', 'label' => 'PN - Pitcairn'],
      ['value' => 'PR', 'label' => 'PR - Puerto Rico'],
      ['value' => 'PS', 'label' => 'PS - Palestinian Territory'],
      ['value' => 'PT', 'label' => 'PT - Portugal'],
      ['value' => 'PW', 'label' => 'PW - Palau'],
      ['value' => 'PY', 'label' => 'PY - Paraguay'],
      ['value' => 'QA', 'label' => 'QA - Qatar'],
      ['value' => 'RE', 'label' => 'RE - Reunion'],
      ['value' => 'RO', 'label' => 'RO - Romania'],
      ['value' => 'RS', 'label' => 'RS - Serbia'],
      ['value' => 'RU', 'label' => 'RU - Russian Federation'],
      ['value' => 'RW', 'label' => 'RW - Rwanda'],
      ['value' => 'SA', 'label' => 'SA - Saudi Arabia'],
      ['value' => 'SB', 'label' => 'SB - Solomon Islands'],
      ['value' => 'SC', 'label' => 'SC - Seychelles'],
      ['value' => 'SD', 'label' => 'SD - Sudan'],
      ['value' => 'SE', 'label' => 'SE - Sweden'],
      ['value' => 'SG', 'label' => 'SG - Singapore'],
      ['value' => 'SH', 'label' => 'SH - Saint Helena'],
      ['value' => 'SI', 'label' => 'SI - Slovenia'],
      ['value' => 'SJ', 'label' => 'SJ - Svalbard and Jan Mayen'],
      ['value' => 'SK', 'label' => 'SK - Slovakia'],
      ['value' => 'SL', 'label' => 'SL - Sierra Leone'],
      ['value' => 'SM', 'label' => 'SM - San Marino'],
      ['value' => 'SN', 'label' => 'SN - Senegal'],
      ['value' => 'SO', 'label' => 'SO - Somalia'],
      ['value' => 'SR', 'label' => 'SR - Suriname'],
      ['value' => 'SS', 'label' => 'SS - South Sudan'],
      ['value' => 'ST', 'label' => 'ST - Sao Tome and Principe'],
      ['value' => 'SV', 'label' => 'SV - El Salvador'],
      ['value' => 'SX', 'label' => 'SX - Sint Maarten'],
      ['value' => 'SY', 'label' => 'SY - Syrian Arab Republic'],
      ['value' => 'SZ', 'label' => 'SZ - Swaziland'],
      ['value' => 'TC', 'label' => 'TC - Turks and Caicos Islands'],
      ['value' => 'TD', 'label' => 'TD - Chad'],
      ['value' => 'TF', 'label' => 'TF - French Southern Territories'],
      ['value' => 'TG', 'label' => 'TG - Togo'],
      ['value' => 'TH', 'label' => 'TH - Thailand'],
      ['value' => 'TJ', 'label' => 'TJ - Tajikistan'],
      ['value' => 'TK', 'label' => 'TK - Tokelau'],
      ['value' => 'TL', 'label' => 'TL - Timor-Leste'],
      ['value' => 'TM', 'label' => 'TM - Turkmenistan'],
      ['value' => 'TN', 'label' => 'TN - Tunisia'],
      ['value' => 'TO', 'label' => 'TO - Tonga'],
      ['value' => 'TR', 'label' => 'TR - Turkey'],
      ['value' => 'TT', 'label' => 'TT - Trinidad and Tobago'],
      ['value' => 'TV', 'label' => 'TV - Tuvalu'],
      ['value' => 'TW', 'label' => 'TW - Taiwan'],
      ['value' => 'TZ', 'label' => 'TZ - Tanzania, United Republic of'],
      ['value' => 'UA', 'label' => 'UA - Ukraine'],
      ['value' => 'UG', 'label' => 'UG - Uganda'],
      ['value' => 'UM', 'label' => 'UM - United States Minor Outlying Islands'],
      ['value' => 'UY', 'label' => 'UY - Uruguay'],
      ['value' => 'UZ', 'label' => 'UZ - Uzbekistan'],
      ['value' => 'VA', 'label' => 'VA - Holy See (Vatican City State)'],
      ['value' => 'VC', 'label' => 'VC - Saint Vincent and the Grenadines'],
      ['value' => 'VE', 'label' => 'VE - Venezuela'],
      ['value' => 'VG', 'label' => 'VG - Virgin Islands, British'],
      ['value' => 'VI', 'label' => 'VI - Virgin Islands, U.S.'],
      ['value' => 'VN', 'label' => 'VN - Vietnam'],
      ['value' => 'VU', 'label' => 'VU - Vanuatu'],
      ['value' => 'WF', 'label' => 'WF - Wallis and Futuna'],
      ['value' => 'WS', 'label' => 'WS - Samoa'],
      ['value' => 'YE', 'label' => 'YE - Yemen'],
      ['value' => 'YT', 'label' => 'YT - Mayotte'],
      ['value' => 'ZA', 'label' => 'ZA - South Africa'],
      ['value' => 'ZM', 'label' => 'ZM - Zambia'],
      ['value' => 'ZW', 'label' => 'ZW - Zimbabwe']
    ];

    /**
     * @var string
     */
    public $languages = [
      ['value' => 'en', 'label' => 'English'],
      ['value' => '', 'label' => '----'],
      ['value' => 'ar', 'label' => 'Arabic'],
      ['value' => 'af', 'label' => 'Afrikaans'],
      ['value' => 'be', 'label' => 'Belarusian'],
      ['value' => 'bg', 'label' => 'Bulgarian'],
      ['value' => 'ca', 'label' => 'Catalan'],
      ['value' => 'zh', 'label' => 'Chinese (Simplified)'],
      ['value' => 'zh_CN', 'label' => 'Chinese (Traditional)'],
      ['value' => 'hr', 'label' => 'Croatian'],
      ['value' => 'cs', 'label' => 'Czech'],
      ['value' => 'da', 'label' => 'Danish'],
      ['value' => 'nl', 'label' => 'Dutch'],
      ['value' => 'et', 'label' => 'Estonian'],
      ['value' => 'fa', 'label' => 'Farsi'],
      ['value' => 'fi', 'label' => 'Finnish'],
      ['value' => 'fr', 'label' => 'French (France)'],
      ['value' => 'fr_CA', 'label' => 'French (Canada)'],
      ['value' => 'de', 'label' => 'German'],
      ['value' => 'el', 'label' => 'Greek'],
      ['value' => 'he', 'label' => 'Hebrew'],
      ['value' => 'hi', 'label' => 'Hindi'],
      ['value' => 'hu', 'label' => 'Hungarian'],
      ['value' => 'is', 'label' => 'Icelandic'],
      ['value' => 'id', 'label' => 'Indonesian'],
      ['value' => 'ga', 'label' => 'Irish'],
      ['value' => 'it', 'label' => 'Italian'],
      ['value' => 'ja', 'label' => 'Japanese'],
      ['value' => 'km', 'label' => 'Khmer'],
      ['value' => 'ko', 'label' => 'Korean'],
      ['value' => 'lv', 'label' => 'Latvian'],
      ['value' => 'lt', 'label' => 'Lithuanian'],
      ['value' => 'mt', 'label' => 'Maltese'],
      ['value' => 'ms', 'label' => 'Malay'],
      ['value' => 'mk', 'label' => 'Macedonian'],
      ['value' => 'no', 'label' => 'Norwegian'],
      ['value' => 'pl', 'label' => 'Polish'],
      ['value' => 'pt', 'label' => 'Portuguese (Brazil)'],
      ['value' => 'pt_PT', 'label' => 'Portuguese (Portugal)'],
      ['value' => 'ro', 'label' => 'Romanian'],
      ['value' => 'ru', 'label' => 'Russian'],
      ['value' => 'sr', 'label' => 'Serbian'],
      ['value' => 'sk', 'label' => 'Slovak'],
      ['value' => 'sl', 'label' => 'Slovenian'],
      ['value' => 'es', 'label' => 'Spanish (Mexico)'],
      ['value' => 'es_ES', 'label' => 'Spanish (Spain)'],
      ['value' => 'sw', 'label' => 'Swahili'],
      ['value' => 'sv', 'label' => 'Swedish'],
      ['value' => 'ta', 'label' => 'Tamil'],
      ['value' => 'th', 'label' => 'Thai'],
      ['value' => 'tr', 'label' => 'Turkish'],
      ['value' => 'uk', 'label' => 'Ukrainian'],
      ['value' => 'vi', 'label' => 'Vietnamese']
    ];

    // Public Methods
    // =========================================================================

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['apiKey'], 'string'],
            [['apiKey'], 'required'],
        ];
    }
}
